#!/bin/sh
PIDFILE=/tmp/tor.pid

case "$1" in
  start)
    echo "Starting lo interface"
    # tor need to bind to localhost
    ifconfig lo up

    echo "Starting TOR"
    # run da tor
    /usr/bin/tor --runasdaemon 1 --pidfile $PIDFILE
    ;;
  stop)
    echo -n "Stopping tor..."
    kill $(cat $PIDFILE)
    ;;
  restart|reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
