#!/bin/sh

case "$1" in
  start)
    echo "Starting Electrum Daemon"
    # run da tor
    su - interlock -c 'proxychains4 -q electrum daemon start 2>&1 > /tmp/electrum.log'
    ;;
  stop)
    echo -n "Stopping Electrum Daemon..."
    su - interlock -c 'electrum daemon stop'
    ;;
  status)
    su - interlock -c 'electrum daemon status'
    ;;
  restart|reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart|status}"
    exit 1
esac

exit $?
